# Generated by Django 4.2.7 on 2023-11-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_result_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='option_a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_b',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_c',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_d',
            field=models.TextField(),
        ),
    ]
