# Generated by Django 4.2.7 on 2023-12-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_activatequiz_activate_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatequiz',
            name='activate_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
