# Generated by Django 4.2.7 on 2023-12-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_practiceq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivateLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate_leaderboard', models.BooleanField(default=False)),
            ],
        ),
    ]
